# fly.toml app configuration file generated for demo-fragrant-breeze-6725 on 2025-07-01T02:41:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-fragrant-breeze-6725'
primary_region = 'eze'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
